### ISSUE TITLE
Add higher taxonomy

### ISSUE THREAD

**Issue by ManonGros** [gbif/embl-adapter#9]
We already have a checklist of the NCBI Taxonomy: https://www.gbif.org/dataset/fab88965-e69d-4491-a04d-e3198b626e52
(scheduled for monthly updates, https://builds.gbif.org/job/ncbi-dwca/).
It would be great to use its content to infer higher taxonomy of scientific names for occurrences: Kingdom, Phylum, Class, Order, Family, Genus

**Comment by timrobertson100** [comment]
I understand the issue here is that we have examples such as [this](https://www.gbif-uat.org/occurrence/2916176375) where we can't do much with the name.

The [original page](https://www.ebi.ac.uk/ena/browser/view/MW555609) for that record has `Taxon:1409` which has the lineage (higher classification) documented [here](https://www.ebi.ac.uk/ena/browser/view/Taxon:1409).

If it is possible through the API we're paging over to get access to that `1409` identifier, you could expand it with the higher classification. Downloading the [ena.zip](ftp://ftp.ebi.ac.uk/pub/databases/ena/taxonomy/sdwca/) at the beginning of the process and keeping a lookup cache keyed on the taxonID might be a way to expand the taxonID of 1409 to the full classification.
